version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev

    ports:
      - "50051:50051"
    restart: unless-stopped
  postgres_db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: sm_db
      POSTGRES_PASSWORD: example