version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/go/src/app
    ports:
      - "50051:50051"
    command: nodemon --exec go run main.go --signal SIGTERM
    restart: unless-stopped
    depends_on:
      - mysql_db


  mysql_db:
    image: mysql:latest
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: mysql_user
      MYSQL_DATABASE: sm_db