version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev

    ports:
      - "50051:50051"
    restart: unless-stopped
  mysql_db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: mysql_user
      MYSQL_DATABASE: sm_db