// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package profile_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProfileServiceClient is the client API for ProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProfileServiceClient interface {
	// CRUD Operation for ProfileInfo
	CreateProfileInfo(ctx context.Context, in *CreateProfileInfoRequest, opts ...grpc.CallOption) (*CreateProfileInfoResponse, error)
	UpdateProfileInfo(ctx context.Context, in *UpdateProfileInfoRequest, opts ...grpc.CallOption) (*UpdateProfileInfoResponse, error)
	DeleteProfileInfo(ctx context.Context, in *DeleteProfileInfoRequest, opts ...grpc.CallOption) (*DeleteProfileInfoResponse, error)
	GetProfileInfo(ctx context.Context, in *GetProfileInfoRequest, opts ...grpc.CallOption) (*GetProfileInfoResponse, error)
}

type profileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileServiceClient(cc grpc.ClientConnInterface) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) CreateProfileInfo(ctx context.Context, in *CreateProfileInfoRequest, opts ...grpc.CallOption) (*CreateProfileInfoResponse, error) {
	out := new(CreateProfileInfoResponse)
	err := c.cc.Invoke(ctx, "/ProfileService/CreateProfileInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) UpdateProfileInfo(ctx context.Context, in *UpdateProfileInfoRequest, opts ...grpc.CallOption) (*UpdateProfileInfoResponse, error) {
	out := new(UpdateProfileInfoResponse)
	err := c.cc.Invoke(ctx, "/ProfileService/UpdateProfileInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) DeleteProfileInfo(ctx context.Context, in *DeleteProfileInfoRequest, opts ...grpc.CallOption) (*DeleteProfileInfoResponse, error) {
	out := new(DeleteProfileInfoResponse)
	err := c.cc.Invoke(ctx, "/ProfileService/DeleteProfileInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) GetProfileInfo(ctx context.Context, in *GetProfileInfoRequest, opts ...grpc.CallOption) (*GetProfileInfoResponse, error) {
	out := new(GetProfileInfoResponse)
	err := c.cc.Invoke(ctx, "/ProfileService/GetProfileInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServiceServer is the server API for ProfileService service.
// All implementations must embed UnimplementedProfileServiceServer
// for forward compatibility
type ProfileServiceServer interface {
	// CRUD Operation for ProfileInfo
	CreateProfileInfo(context.Context, *CreateProfileInfoRequest) (*CreateProfileInfoResponse, error)
	UpdateProfileInfo(context.Context, *UpdateProfileInfoRequest) (*UpdateProfileInfoResponse, error)
	DeleteProfileInfo(context.Context, *DeleteProfileInfoRequest) (*DeleteProfileInfoResponse, error)
	GetProfileInfo(context.Context, *GetProfileInfoRequest) (*GetProfileInfoResponse, error)
	mustEmbedUnimplementedProfileServiceServer()
}

// UnimplementedProfileServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProfileServiceServer struct {
}

func (UnimplementedProfileServiceServer) CreateProfileInfo(context.Context, *CreateProfileInfoRequest) (*CreateProfileInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProfileInfo not implemented")
}
func (UnimplementedProfileServiceServer) UpdateProfileInfo(context.Context, *UpdateProfileInfoRequest) (*UpdateProfileInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfileInfo not implemented")
}
func (UnimplementedProfileServiceServer) DeleteProfileInfo(context.Context, *DeleteProfileInfoRequest) (*DeleteProfileInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProfileInfo not implemented")
}
func (UnimplementedProfileServiceServer) GetProfileInfo(context.Context, *GetProfileInfoRequest) (*GetProfileInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfileInfo not implemented")
}
func (UnimplementedProfileServiceServer) mustEmbedUnimplementedProfileServiceServer() {}

// UnsafeProfileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfileServiceServer will
// result in compilation errors.
type UnsafeProfileServiceServer interface {
	mustEmbedUnimplementedProfileServiceServer()
}

func RegisterProfileServiceServer(s grpc.ServiceRegistrar, srv ProfileServiceServer) {
	s.RegisterService(&ProfileService_ServiceDesc, srv)
}

func _ProfileService_CreateProfileInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProfileInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).CreateProfileInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProfileService/CreateProfileInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).CreateProfileInfo(ctx, req.(*CreateProfileInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_UpdateProfileInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).UpdateProfileInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProfileService/UpdateProfileInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).UpdateProfileInfo(ctx, req.(*UpdateProfileInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_DeleteProfileInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProfileInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).DeleteProfileInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProfileService/DeleteProfileInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).DeleteProfileInfo(ctx, req.(*DeleteProfileInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_GetProfileInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GetProfileInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProfileService/GetProfileInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GetProfileInfo(ctx, req.(*GetProfileInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProfileService_ServiceDesc is the grpc.ServiceDesc for ProfileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProfileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProfileInfo",
			Handler:    _ProfileService_CreateProfileInfo_Handler,
		},
		{
			MethodName: "UpdateProfileInfo",
			Handler:    _ProfileService_UpdateProfileInfo_Handler,
		},
		{
			MethodName: "DeleteProfileInfo",
			Handler:    _ProfileService_DeleteProfileInfo_Handler,
		},
		{
			MethodName: "GetProfileInfo",
			Handler:    _ProfileService_GetProfileInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/profile_pb/profile.proto",
}
