// Code generated by sqlc. DO NOT EDIT.

package sql_db

import (
	"database/sql"
)

type ExtraInfo struct {
	ID         int64          `json:"id"`
	University sql.NullString `json:"university"`
	AboutMe    sql.NullString `json:"about_me"`
	UserID     sql.NullInt64  `json:"user_id"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

type ProfileInfo struct {
	ID        int64          `json:"id"`
	FirstName sql.NullString `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	// Must be valid email
	Email sql.NullString `json:"email"`
	// Must be valid phone number
	PhoneNumber sql.NullString `json:"phone_number"`
	// Url of the image
	ProfileImg sql.NullString `json:"profile_img"`
	UserID     sql.NullInt64  `json:"user_id"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID        int64          `json:"id"`
	Username  sql.NullString `json:"username"`
	Password  sql.NullString `json:"password"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}
